Change dracut command

diff --git a/__frzr-kernel b/__frzr-kernel
--- a/__frzr-kernel
+++ b/__frzr-kernel
@@ -299,7 +299,8 @@ frzr_kernel() {
 			STATE="INITRAMFS"
 			;;
 		"INITRAMFS")
-			if ! mkinitcpio -c "${BASH_SOURCE%/*}/../lib/frzr/mkinitcpio.conf" -g "${EFI_MOUNT_PATH}/initramfs-frzr.img" -k "${KERNEL_NAME}" -r "${MODULES_DIR}"; then
+
+			if ! dracut --force --filesystems "overlay btrfs" --strip --aggressive-strip --fstab --reproducible --kver ${KERNEL_NAME} --kmoddir "${MODULES_DIR}/lib/modules/${KERNEL_NAME}" "${EFI_MOUNT_PATH}/initramfs-frzr.img"; then
 				#TASK_ERROR=1
 				#TASK_ERROR_MSG="ERROR: Could not generate a valid initramfs"
 				#STATE="FAIL"
@@ -307,6 +308,15 @@ frzr_kernel() {
 				#continue
 				echo "WARNING: initramfs might not be complete"
 			fi
+
+			#if ! mkinitcpio -c "${BASH_SOURCE%/*}/../lib/frzr/mkinitcpio.conf" -g "${EFI_MOUNT_PATH}/initramfs-frzr.img" -k "${KERNEL_NAME}" -r "${MODULES_DIR}"; then
+			#	#TASK_ERROR=1
+			#	#TASK_ERROR_MSG="ERROR: Could not generate a valid initramfs"
+			#	#STATE="FAIL"
+			#	#send_data
+			#	#continue
+			#	echo "WARNING: initramfs might not be complete"
+			#fi
 
 			if ! cp "$modulesdir/vmlinuz" "${EFI_MOUNT_PATH}/vmlinuz-frzr"; then
 				TASK_ERROR=1
