refactor: fix errors

diff --git a/__frzr-deploy b/__frzr-deploy
--- a/__frzr-deploy
+++ b/__frzr-deploy
@@ -190,7 +190,7 @@ main() {
 				SUBVOL="${DEPLOY_PATH}/${NAME}"
 				IMG_FILE="${MOUNT_PATH}/${FILE_NAME}"
 
-				if [ -e ${SUBVOL} ]; then
+				if [ -e "${SUBVOL}" ]; then
 					# Only allow deleting the subvolume if we are booted in the installer.
 					if [ "$UPGRADE" -eq 0 ]; then
 						MSG="${NAME} is already installed, would you like to delete this and re-deploy?"
@@ -266,6 +266,7 @@ main() {
 			fi
 
 			# Install the deployment from the downloaded file $IMG_FILE and place the deployed image in $DEPLOY_PATH
+			TASK_MSG="Installing the downloaded deployment"
 			local install_result=$(install_image "${IMG_FILE}" "${DEPLOY_PATH}")
 			if echo "${install_result}" | grep -Fqx 'ERROR'; then
 				TASK_ERROR=1
@@ -324,25 +325,27 @@ main() {
 
 			# verify the subvolume integrity
 			TASK_MSG="Checking integrity of deployed image"
-			if btrfs scrub start -Bdr "${SUBVOL}"; then
-				# Verify the system installation status, check for device quirks, and prepare for cleanup
-				# Check if the FIRMWARE_OVERRIDE variable is set by the install media, if so enable firmware overrides
-				if [ -n "${FIRMWARE_OVERRIDE}" ]; then
-					echo "export USE_FIRMWARE_OVERRIDES=1" >${MOUNT_PATH}/etc/device-quirks.conf
+			if [ -z "$FRZR_SKIP_CHECK" ]; then
+				if ! btrfs scrub start -Bdr "${SUBVOL}"; then
+					TASK_ERROR=1
+					TASK_ERROR_MSG="FS check on btrfs subvolume '$SUBVOL' failed: image integrity compromised"
+					STATE="FAIL"
 				fi
-
-				# Run frzr-tweaks to execute the device-quirks to be supplied by the deployed images
-				#frzr-tweaks # TODO: pass the root as an argument and in the script default to "/"
-
-				# Run frzr-initramfs to create mkinicpio.conf and build an initramfs
-				#frzr-initramfs # TODO: review, this writes mkinitcpio.conf, make sure it stays aligned with the image one
-				echo "Entering Cleanup Case"
-				STATE="CLEANUP"
-			else
-				TASK_ERROR=1
-				TASK_ERROR_MSG="FS check on btrfs subvolume '$SUBVOL' failed: image integrity compromised"
-				STATE="FAIL"
 			fi
+
+			# Verify the system installation status, check for device quirks, and prepare for cleanup
+			# Check if the FIRMWARE_OVERRIDE variable is set by the install media, if so enable firmware overrides
+			#if [ -n "${FIRMWARE_OVERRIDE}" ]; then
+			#	echo "export USE_FIRMWARE_OVERRIDES=1" >${MOUNT_PATH}/etc/device-quirks.conf
+			#fi
+
+			# Run frzr-tweaks to execute the device-quirks to be supplied by the deployed images
+			#frzr-tweaks # TODO: pass the root as an argument and in the script default to "/"
+
+			# Run frzr-initramfs to create mkinicpio.conf and build an initramfs
+			#frzr-initramfs # TODO: review, this writes mkinitcpio.conf, make sure it stays aligned with the image one
+			echo "Entering Cleanup Case"
+			STATE="CLEANUP"
 			;;
 		"CLEANUP")
 			TASK_STATE="CLEANUP"
@@ -452,11 +455,13 @@ main() {
 		"FAIL")
 			# This state should only be used if the installation failed
 
-			if is_btrfs_subvolume "${SUBVOL}"; then
-				local deployment_removal_result=$(btrfs_filtered_subvolume_recursive_delete "${SUBVOL}" "deployments")
-				if echo "${deployment_removal_result}" | grep -Fqx "ERROR"; then
-					TASK_ERROR=1
-					TASK_ERROR_MSG="Could not delete the new (errored) deployment: ${deployment_removal_result}"
+			if [ -d "${SUBVOL}" ]; then
+				if is_btrfs_subvolume "${SUBVOL}"; then
+					local deployment_removal_result=$(btrfs_filtered_subvolume_recursive_delete "${SUBVOL}" "deployments")
+					if echo "${deployment_removal_result}" | grep -Fqx "ERROR"; then
+						TASK_ERROR=1
+						TASK_ERROR_MSG="Could not delete the new (errored) deployment: ${deployment_removal_result}"
+					fi
 				fi
 			fi
 
